/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "./types";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
